# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5-node-browsers

    working_directory: ~/fir

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            ./run_all_tests.rb
  build_ruby_2_4:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4-node-browsers

    working_directory: ~/fir

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            ./run_all_tests.rb
  build_ruby_2_3:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.3-node-browsers

    working_directory: ~/fir

    steps:
      - checkout
      - run:
          name: run tests
          command: |
            ./run_all_tests.rb
